version: '3'
dotenv: [.env]

vars:
  PACKAGE_IMPORT_NAME: bank_prediction
  PYTHON_VERSION: 3.12

tasks:
  create-venv:
    desc: Create a virtual environment
    cmds:
      - uv venv -p {{.PYTHON_VERSION}} .venv
    silent: false

  sync-dev:
    desc: Sync project dependencies with optionals
    cmds:
      - rm -rf .venv
      - task: create-venv
      - uv sync --extra dev

  sync-test:
    desc: Sync only test dependencies
    cmds:
        - rm -rf .venv
        - task: create-venv
        - uv sync --extra test
        # - source .venv/Scripts/activate && uv sync --extra test # Activate and sync

  lint:
    desc: Run pre-commit hooks
    cmds:
      - uv run pre-commit run --all-files
  clean:
    desc: "Clean up build artifacts, caches, and temporary files"
    cmds:
      - rm -rf dist build coverage.xml test-reports tests/mlruns test-house_price
      - find . -type d \( -name "*cache*" -o -name "*.dist-info" -o -name "*.egg-info" -o -name "*htmlcov" \) -not -path "*env/*" -exec rm -r {} + || true
      - find . -type f -name "*.pyc" -not -path "*env/*" -exec rm {} +
    silent: true


  help:
    desc: Print all tasks defined in the Taskfile
    cmd: task -l
    silent: true

  default:
    cmds:
      - task: help
    silent: true
